### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by nevioth** [mathieudutour/git-sketch-plugin#18]
Probably not an issue per se, but is there a manual for people who're not well-versed with git? 
- where does 'init-repo' push to? 
- where does 'push' go to? Is it using my git account if i'm logged in on www?
- how does the creating pngs for diffs work – how do I view them?
- troubleshooting

thanks for your time

**Comment by mathieudutour** [comment]
That's a good idea. Maybe it could fit in a FAQ. I don't really have time to work on that right now, but if you want to give it a shot, I'd be happy to help you on the way.

BTW, a really nice intro to git: https://try.github.io/levels/1/challenges/1

**Comment by iamhenry** [comment]
A simple tutorial would be very helpful. I've been trying to use this for the past 2 days without any success.

**Comment by aryaman765** [comment]
@iamhenry @nevioth I am a product designer who spent a few days understanding this and getting it to work. Till a more elaborate tutorial is available, I am writing this basic tutorial. @mathieudutour please correct me if I am wrong.

**Background** (ignore if familiar with git and github)
- There are three things involved here : git, github and this plugin
- Git is a method, a system for version control.
- Git clients are software that use git and enhance it in some way. Both this plugin and github are git clients, which enhance your version control experience in diff ways.
- Github puts your code online. Its called a remote. Here your files is stored on the cloud.
- This plugin makes it easier for designers to control the remote. Without this plugin, one would have to do it via the terminal.

**Tutorial**
Step 1)
You need to install git on your machine, then create the connection between git and github so they can talk to each other. 
https://help.github.com/articles/set-up-git/

This connection is created by telling git (installed on your machine) the credentials to your github (cloud). Ignore this step if you don't use 2-factor authentication to login to GitHub. If you are trying to get this plugin to work for an organisation, chances are that you will have 2-factor authentication enabled. So in this scenario, your id and password won't suffice. You need to create an SSH key. Its like the next level of password.
https://help.github.com/articles/generating-an-ssh-key/

Step 2)
Create yourGitHub Repository. Once you create it, go to its settings and copy the URL.
Now, have one folder where your project is stored. Open your sketch file which should be saved in that folder. Now, go on with the demo given by @mathieudutour . When you do init repo, paste the URL of your repository. Make sure you are using the correct format (SSH or HTTPS) according to your authentication method.

Step 3) Before you push, cache your credentials if you are using HTTPS. https://help.github.com/articles/caching-your-github-password-in-git/. 

Thats it, you should be able to get it working!

**Comment by mathieudutour** [comment]
Nice! 
Some clarifications though:
- git is a **distributed** version control system. It means that your repository (folder) live in different places at the same time. One of those places is your computer (local directory), another one is the github servers (remote). You can have others as well but it's beyond the scope of this discussion. 
  To tell your computer that your folder should be tracked using git: `Plugins > Git > Advanced > Init git repo`. 
  At this point you will be asked for the URL of the remote. Go to github, create a new repo and copy paste the URL of your repository in the plugin. Make sure you are using the correct format (SSH or HTTPS) according to your authentication method.
- The different places are not sync automatically (if you would want that, which you don't believe me), use dropbox. Git allows you to sync your data only when you want to.
- The first "way" to sync your data is when you have made changes on your local directory and that you want to **push** them to the remote (github in this case). You first have to **commit** your changes. When you commit your changes, you are saying to git: "Ok, I like what I have done now, take a snapshot of my files and store it". You need to enter a message to describe the changes you've made. This will allow your co-workers (and yourself) to remember what happened at that point.
  You can then push. To do that, you need to connect to your remote (github). Because not everybody can push on your repo, you need to tell git about your github credentials so that github knows that it's you. 
  https://help.github.com/articles/set-up-git/
  https://help.github.com/articles/caching-your-github-password-in-git/
- The second way to sync your data is when someone else has made some changes and pushed them to the remote. You now need to **pull** the changes from the remote to your local directory.

**Comment by iamhenry** [comment]
@mathieudutour @aryaman765 Thank you guys for taking the time to write this and explain it more in detail. I will give this a shot.

@mathieudutour  Before I do that, how does Github handle Diff when you have multiple artboards in a single page? I would mainly like to use this workflow so that I can work more efficiently with teams and have some sort of "PR" for design that allows the team to know which files have been approved.

Thanks again guys.

**Comment by mathieudutour** [comment]
It's generating 1 png per artboards, independently of if they are in the same page or not. Just be careful if some of your artboards have the same name

**Comment by iamhenry** [comment]
Thanks for clearing that up. Excited to try it out later today on my free time.

**Comment by mathieudutour** [comment]
I wrote a bit more docs here: https://github.com/mathieudutour/git-sketch-plugin/tree/master/docs
Closing this for now, but I'd be really happy to accept any contribution to improve them :)
