### ISSUE TITLE
Trying to use with company enterprise git

### ISSUE THREAD

**Issue by grigely** [mathieudutour/git-sketch-plugin#37]
I'm hoping I can get some help. I'm working on an internal, company git and keep getting the following:

<img width="532" alt="screen shot 2016-06-08 at 5 46 10 pm" src="https://cloud.githubusercontent.com/assets/10439220/15912225/0fc76eea-2da1-11e6-982e-73c6e6cf2dcd.png">

The URL is the address of my internal org's git. I should also mention this requires a login. Any help would be greatly appreciated!

**Comment by mathieudutour** [comment]
can't you store the credentials? (https://help.github.com/articles/caching-your-github-password-in-git/)

**Comment by aryaman765** [comment]
Facing the same issue. I this is happening because the username is common to both your enterprise and personal account. Trying to fix this by entering my e-mail ID for enterprise. Will post an update if it works

**Comment by aryaman765** [comment]
Trying to change the repo getting this error

<img width="532" alt="screen shot 2016-06-09 at 1 29 33 pm" src="https://cloud.githubusercontent.com/assets/19321216/15924045/db7c7ac4-2e4d-11e6-97c6-f86b990dff07.png">

**Comment by mathieudutour** [comment]
what do you mean change the repo?

**Comment by aryaman765** [comment]
I am facing the authentication problem mentioned by @buughost 
Till I figure how to get it working on enterprise, I want to try it out on my personal account. Thus, I want to switch the repo I am working with to a one on my personal account. When I do init git repo, I paste the URL of the repo I am trying to shift to, it throws this error.

PS I am a designer new to git, love this idea and trying to get it to work for my organisation. Thanks.

**Comment by mathieudutour** [comment]
because your repo is already initialized, you can't initialized it again.

To change the remote: Plugins > Git > Advanced > Terminal and run `git remote set-url origin NEW_URL`

**Comment by aryaman765** [comment]
Thanks!

**Comment by aryaman765** [comment]
@mathieudutour Need more help!

I will tell you the whole story, please point where I am going wrong.
1) I am part of an organisation on Github, where I have created a private repo
2) I open Sketch, do git init and point it to the aforementioned private repo
3) I add the file I am working with to git
4) I make a new branch, make some changes, save the file
5) I commit the changes. All is fine till here.
6) When I try to push, it says authentication failed, but the credentials saved in my keychain are correct, I have verified that.

What mistake could I be making here? Is it something to do with my organization's security? Or because its a private repo?

**Comment by mathieudutour** [comment]
if you go to the terminal and do `git push` what happen?

**Comment by aryaman765** [comment]
push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: The current branch aryaman has no upstream branch.
To push the current branch and set the remote as upstream, use

```
git push --set-upstream origin aryaman
```

**Comment by mathieudutour** [comment]
try 

```
git push --set-upstream origin aryaman
git -c push.default=current push
```

**Comment by aryaman765** [comment]
Hi,
I realized my organization uses two factor authentication hence we will need to use SSH key. How to tell the plugin to use my key?

**Comment by mathieudutour** [comment]
not sure, maybe changing the remote to use ssl instead of https (starting with `git@` instead of `https://`)

**Comment by aryaman765** [comment]
Hey, got it working. Want to understand how you are making it work? are you generating PNGs of the artboards or are you using the metadata that sketch provides to tell me about conflicts?

**Comment by mathieudutour** [comment]
pngs of artboards

**Comment by grigely** [comment]
Got it to work using the keychain part! thanks so much!
