### ISSUE TITLE
a Way to exclude pages from pretty diffs

### ISSUE THREAD

**Issue by zeroxme** [mathieudutour/git-sketch-plugin#40]
Would be great to be able to exclude some pages from pretty diffs

**Comment by mathieudutour** [comment]
you already can:
create a `.gitignore` file at the root of your directly and add the files you want to ignore there.

Or were you thinking about something else?

**Comment by zeroxme** [comment]
I mean inside sketch. I have multiple pages so when I run generate diffs. it creates it for all pages. I want to exclude some pages. In this case I want to exclude not used page

<img width="225" alt="screen shot 2016-06-27 at 1 55 23 pm" src="https://cloud.githubusercontent.com/assets/3534296/16378892/d71c414c-3c6e-11e6-924d-38d35bc4fef1.png">

**Comment by mathieudutour** [comment]
Interesting.

I'll have a think about how it could be done.

**Comment by PatrickDattilio** [comment]
@mathieudutour We would love the option of toggling specific artboards as well.

Perhaps when running "Generate files for pretty diff" (manually or via the checkbox on the commit window) if there is more than one page/artboard, you could popup an additional dialog. This dialog could list checkboxes for each Page and Artboard. Clicking a page checkbox enables/disables all the child artboards, clicking an artboard enables it to be exported in a diff. 
I believe the relevant information can be retrieved using:

`sketchtool list artboards <doc.sketch>`
`sketchtool list pages <doc.sketch>`

**Comment by mathieudutour** [comment]
It can indeed be retrieved with this command.

The checkboxes are probably too manual and don't work well with team work
(one will check those boxes while another one will check some others and
the diffs will be fucked).

I was more thinking about a file (maybe `.sketchignore`) that you add to
the repo. It would list the artboards that you don't want to generate.

Then I could potentially create a UI to select the artboards but that's
secondary

On Aug 17, 2016, at 2:38 AM, Patrick Dattilio notifications@github.com
wrote:

@mathieudutour https://github.com/mathieudutour We would love the option
of toggling specific artboards as well.

Perhaps when running "Generate files for pretty diff" (manually or via the
checkbox on the commit window) if there is more than one page/artboard, you
could popup an additional dialog. This dialog could list checkboxes for
each Page and Artboard. Clicking a page checkbox enables/disables all the
child artboards, clicking an artboard enables it to be exported in a diff.
I believe the relevant information can be retrieved using:

sketchtool list artboards <doc.sketch>
sketchtool list pages <doc.sketch>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/mathieudutour/git-sketch-plugin/issues/40#issuecomment-240281726,
or mute the thread

**Comment by PatrickDattilio** [comment]
We have some large Sketch files with a dozen pages, each containing dozens of artboards. To make a change usinga .sketchignore, they would need to first update the .sketchignore file adding all artboards not used in the current feature, update the artboard, then commit? 

Seems like a reasonable way to do things, though once you start hitting dozens of artboards, adding/deleting them from .sketchignore will become painful if done manually.

*Edit - The [Zeplin.io plugin](https://github.com/zeplin/zeplin-sketch-plugin) has an export button "Export selected artboards". You could borrow this option, so we could select only artboards that changed.

**Comment by mathieudutour** [comment]
Indeed. To mitigate this, you would be able to add "blob", for example
`ignore-*` would ignore all the artboards starting with "ignore-".
Does that sounds reasonable?

On Aug 17, 2016, at 2:38 PM, Patrick Dattilio notifications@github.com
wrote:

We have some large Sketch files with a dozen pages, each containing dozens
of artboards. To make a change usinga .sketchignore, they would need to
first update the .sketchignore file adding all artboards not used in the
current feature, update the artboard, then commit?

Seems like a reasonable way to do things, though once you start hitting
dozens of artboards, adding/deleting them from .sketchignore will become
painful if done manually.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/mathieudutour/git-sketch-plugin/issues/40#issuecomment-240398360,
or mute the thread

**Comment by PatrickDattilio** [comment]
That seems great as a workaround.

**Comment by PatrickDattilio** [comment]
If I have artboard A, B, C, D and I made a change to B and wanted to create a pr that only showed my changes, would I then need to rename A,C,D to ignore-A, ignore-C, ignore-D? Then commit/generate images? And then if I made a change to D in another branch, revert the name change on D, and rename B to ignore-B?

**Comment by Davst** [comment]
Should be based on selection like the Zeplin plugin

**Comment by mathieudutour** [comment]
Just to be clear: what the use case for ignoring artboards?
 I see 2:
- ignoring "research" artboards and ignoring "grouping" artboards which are not part of the design
- hack around a current limitation which make you push every artboards even though they didn't change

I'm perfectly fine with the first use case, not with the second. The fix for the second use case is to check (not manually of course) if the generated images are the same and in that case, discard the new generated.

**Comment by mathieudutour** [comment]
I just fixed the second case

**Comment by PatrickDattilio** [comment]
The use case for ignoring artboards is the first case. Our design process has a bunch of different artboards for a single design which go through  review, and usually one moves forward. I don't think our designers want to just delete that work. Perhaps a separate page for that review step, combined with your proposed page-level ignoring and now generating images for only changed artboards, will work.

**Comment by mathieudutour** [comment]
fixed in 0.5 🎉 
Check out the example here: https://github.com/mathieudutour/git-sketch-plugin/tree/master/example
