### ISSUE TITLE
Switch and new branch

### ISSUE THREAD

**Issue by HYPD** [mathieudutour/git-sketch-plugin#6]
Sorry in advance if this is wrong, im semi-new to git.

When I use New Banch, it only makes this branch locally, I have to go to repo online and create a branch under exactly the same name. Or I cant push. Is there any way we can do this once in sketch and then just push the changes through the plugin?

When Switching branch, i'm finding that sketch is committing and pushing changes to the branch I switched to, and the one I was working on. Therefore im finding things publishing on 2 or 3 branches. This is a real pain point for me.

**Comment by mathieudutour** [comment]
Indeed, when you create a branch locally, it does it only locally until you push your branch. But you shouldn't have to create it online to be able to push.

> When Switching branch, i'm finding that sketch is committing and pushing changes to the branch I switched to, and the one I was working on. Therefore im finding things publishing on 2 or 3 branches. This is a real pain point for me.

That's shouldn't be possible, you cannot commit in two branches as the same time. But depending on your git config, you might push all your branches at once (instead of just the working one). I don't have time to go in depth now but do read this thread: http://stackoverflow.com/questions/948354/default-behavior-of-git-push-without-a-branch-specified and get back to me if you still have any issue.

**Comment by mathieudutour** [comment]
Is this still an issue?
