### ISSUE TITLE
Export in hidden folder will leave stray files on users systems.

### ISSUE THREAD

**Issue by renzska** [mathieudutour/git-sketch-plugin#73]
Because folders that begin with a period are hidden by default, if a user uses your tool, it will leave hidden files on the machine. I vote that the files not be hidden by default and instead make it an option.

**Comment by mathieudutour** [comment]
it is an option already. I'd prefer the default to be hidden because it's not files that you should care about, it's only useful for github.

But I have no strong feeling about it. I'll leave this issue open to see what people think about it.

people coming on this thread, please vote on the issue:
- 👍  for **not** hidden by default
- 👎  for hidden by default

**Comment by 0xcaff** [comment]
It seems the prevailing sentiment is to keep things the way they are.

![image](https://user-images.githubusercontent.com/3277097/35300158-a8aaa0cc-0055-11e8-9492-1894056627c4.png)
